name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: target/userbook-maven-0.0.1-SNAPSHOT.jar